### ISSUE TITLE
macos build action support

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3599]
github actions support building on macos. preliminary testing shows this config is a good start (though our cmake config isn't equipped to deal with clang):
```yml
  build-macos:
    name: MacOS package
    runs-on: macos-12
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          brew install ccache
          brew install ninja
          pip install 'sphinx<4.4.0'
      - name: Clone DFHack
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Fetch ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ccache-macos-12-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ccache-macos-12-${{ github.ref_name }}
            ccache-macos-12
      - name: Set up environment
        id: env_setup
        run: |
          echo "CCACHE_DIR=${HOME}/.ccache" >> $GITHUB_ENV
      - name: Configure DFHack
        run: |
          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DDFHACK_BUILD_ARCH=64 \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DBUILD_DOCS:BOOL=1 \
            -DCMAKE_INSTALL_PREFIX=build/macos_output
      - name: Build DFHack
        run: |
          ninja -C build install
          ccache --max-size 50M
          ccache --cleanup
          ccache --show-stats
      - name: Format artifact name
        id: artifactname
        run: |
          echo name=$(date +%Y%m%d)-$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dfhack-macos-build-${{ steps.artifactname.outputs.name }}
          path: build/macos_output/*
```
